// Auto-generated by script. Do not edit manually.
export type ProjectCategory = "personal" | "nimiq" | "external";
export interface ProjectEntry {
  category: ProjectCategory;
  owner: string;
  name: string;
  nameWithOwner: string;
  role: string;
  summary: string;
  links: { label: string; url: string }[];
  timeline: { start: string | null; end: string | null; duration: string | null; commitCount: number };
  stack: string[];
  highlights: { label: string; count: number; examples: string[] }[];
  collaboration: { pullRequests: Record<string, number>; issues: Record<string, number>; samplePRs: { title: string; url: string; state: string }[]; sampleIssues: { title: string; url: string; state: string }[] };
  meta: { stars: number | null; license: string | null; createdAt: string | null; updatedAt: string | null };
  impact: string;
}

export const PROJECTS: ProjectEntry[] = [
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-ui",
    nameWithOwner: "onmax/nimiq-ui",
    role: "Creator & Lead Maintainer",
    summary: "Focuses on tooling & dependency upkeep and bug fixing contributions. Recent commit: docs: update VitePress theme guide for v2 compatibility. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-ui" },
      { label: "Live", url: "https://onmax.github.io/nimiq-ui/" },
    ],
    timeline: { start: "2024-01-10", end: "2025-09-24", duration: "1y 8m", commitCount: 1150 },
    stack: ["CSS"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 122, examples: ["chore: release v1.0.0-beta.100", "chore: added colors to text hoverable"] },
      { label: "Bug fixing", count: 39, examples: ["fix: adjust margin and icon opacity in sidebar and headline components", "fix: build"] },
      { label: "Feature development", count: 23, examples: ["feat: NqLinks with auto icons, first blue rest secondary", "feat: add NqLinks component with docs"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 1, "OPEN": 0, "CLOSED": 1 },
      issues: { "OPEN": 59, "CLOSED": 8 },
      samplePRs: [
        { title: "feat(theme): Update active sidebar item styling", url: "https://github.com/onmax/nimiq-ui/pull/69", state: "CLOSED" },
        { title: "feat: Use lh units for typography margins", url: "https://github.com/onmax/nimiq-ui/pull/66", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "Fix switch in Safari", url: "https://github.com/onmax/nimiq-ui/issues/18", state: "OPEN" },
        { title: "Add easing ", url: "https://github.com/onmax/nimiq-ui/issues/17", state: "OPEN" },
        { title: "Add `scroll-padding-block` in a `textarea` ", url: "https://github.com/onmax/nimiq-ui/issues/16", state: "OPEN" },
      ],
    },
    meta: { stars: 2, license: null, createdAt: "2023-11-20", updatedAt: "2025-09-24" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "albatross-rpc-client-ts",
    nameWithOwner: "onmax/albatross-rpc-client-ts",
    role: "Creator & Lead Maintainer",
    summary: "A fully typed Nimiq RPC client for TypeScript.",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/albatross-rpc-client-ts" },
      { label: "Live", url: "https://nimiq.github.io/developer-center/build/rpc-docs/" },
    ],
    timeline: { start: "2023-03-14", end: "2025-09-12", duration: "2y 6m", commitCount: 371 },
    stack: ["TypeScript", "albatross", "nimiq", "rpc-client"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 76, examples: ["chore: release v1.0.0-beta.35", "chore: release v1.0.0-beta.34"] },
      { label: "Feature development", count: 15, examples: ["Merge pull request #71 from onmax/add-mock-websocket", "feat: improve schema validation workflow"] },
      { label: "Bug fixing", count: 14, examples: ["fix: add explicit type annotations for JSR slow types", "fix: resolve 7 more AI-detected schema validation issues"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 4, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 5, "CLOSED": 13 },
      samplePRs: [
        { title: "Simplify types", url: "https://github.com/onmax/albatross-rpc-client-ts/pull/37", state: "MERGED" },
        { title: "Onmax/testing no ws", url: "https://github.com/onmax/albatross-rpc-client-ts/pull/52", state: "MERGED" },
        { title: "feat: Add Valibot validation with JSON schema export", url: "https://github.com/onmax/albatross-rpc-client-ts/pull/78", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "Rename to albatross-rpc-client-ts or something with `albatross`", url: "https://github.com/onmax/albatross-rpc-client-ts/issues/32", state: "CLOSED" },
        { title: "Enable `yarn test`", url: "https://github.com/onmax/albatross-rpc-client-ts/issues/28", state: "CLOSED" },
        { title: "Removed getEpochNumberAt", url: "https://github.com/onmax/albatross-rpc-client-ts/issues/49", state: "CLOSED" },
      ],
    },
    meta: { stars: 2, license: null, createdAt: "2023-03-14", updatedAt: "2025-09-12" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq.com-sources",
    nameWithOwner: "onmax/nimiq.com-sources",
    role: "Creator & Lead Maintainer",
    summary: "Script to auto-generate sources used in nimiq.com",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq.com-sources" },
      { label: "Live", url: "https://nimiq.com" },
    ],
    timeline: { start: "2023-02-11", end: "2025-04-14", duration: "2y 2m", commitCount: 300 },
    stack: ["Python", "python3", "scripts", "huggingface-transformers", "sentiment-analysis", "twitter-api", "github-api", "github-stats"],
    highlights: [
      { label: "General maintenance", count: 3, examples: ["commit and push the rigth file in lunarcrush", "optimized github stats by ignoring unused repos"] },
      { label: "Feature development", count: 1, examples: ["added devcontainer environment"] },
      { label: "Bug fixing", count: 1, examples: ["fixed tweets sentiment"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 1, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
        { title: "GitHub stats", url: "https://github.com/onmax/nimiq.com-sources/pull/1", state: "MERGED" },
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 3, license: null, createdAt: "2022-10-25", updatedAt: "2025-04-14" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "unocss-preset-onmax",
    nameWithOwner: "onmax/unocss-preset-onmax",
    role: "Creator & Lead Maintainer",
    summary: "Focuses on tooling & dependency upkeep and feature development contributions. Recent commit: chore: release v1.0.0-beta.43. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/unocss-preset-onmax" },
      { label: "Live", url: "https://onmax.github.io/unocss-preset-onmax/" },
    ],
    timeline: { start: "2025-03-06", end: "2025-09-22", duration: "6m", commitCount: 176 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 68, examples: ["chore: release v1.0.0-beta.43", "chore: release v1.0.0-beta.42"] },
      { label: "Feature development", count: 36, examples: ["feat: add extendColors option to PresetLightDarkOptions and update related functionality; add test cases and example HTML/CSS", "feat: update matched.txt and output.css for improved styling and add focus-visible variants in tests"] },
      { label: "Bug fixing", count: 31, examples: ["fix: allow nested variants", "fix: update selector syntax for better specificity in presetOnmax"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 17, "CLOSED": 3 },
      samplePRs: [
      ],
      sampleIssues: [
        { title: "improve hocus", url: "https://github.com/onmax/unocss-preset-onmax/issues/20", state: "OPEN" },
        { title: "allow write var with multiple values", url: "https://github.com/onmax/unocss-preset-onmax/issues/19", state: "OPEN" },
        { title: "`text=\"f-12/16 current\"` does not work", url: "https://github.com/onmax/unocss-preset-onmax/issues/18", state: "OPEN" },
      ],
    },
    meta: { stars: 1, license: null, createdAt: "2025-03-06", updatedAt: "2025-09-22" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-auth",
    nameWithOwner: "onmax/nimiq-auth",
    role: "Creator & Lead Maintainer",
    summary: "Focuses on tooling & dependency upkeep and general maintenance contributions. Recent commit: chore(nuxt): fixed types for auth-utils. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-auth" },
      { label: "Live", url: "https://nimiq-auth.nuxt.dev/" },
    ],
    timeline: { start: "2025-01-29", end: "2025-02-21", duration: "under 1m", commitCount: 148 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 42, examples: ["chore: init plugin in better auth", "chore: added logs in login errors and warns"] },
      { label: "General maintenance", count: 4, examples: ["lazy", "a"] },
      { label: "Documentation", count: 3, examples: ["docs: added nimiq-css", "docs: setup structure and wrote some content"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-01-29", updatedAt: "2025-06-17" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-identicons",
    nameWithOwner: "onmax/nimiq-identicons",
    role: "Creator & Lead Maintainer",
    summary: "The modern implementation for Nimiq Identicons",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-identicons" },
      { label: "Live", url: "https://onmax.github.io/nimiq-identicons/" },
    ],
    timeline: { start: "2024-10-24", end: "2025-04-25", duration: "6m", commitCount: 112 },
    stack: ["JavaScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 79, examples: ["chore: update SVG files for identicons and enhance Builder component layout", "chore: consolidate TypeScript configuration by removing unused files and updating settings"] },
      { label: "Feature development", count: 10, examples: ["feat: add shouldValidateAddress option and update identicon generation", "feat: update Identicon material options, enhance styling, and upgrade dependencies"] },
      { label: "Bug fixing", count: 9, examples: ["fix: make to convert base 64 the svg", "fix: make to convert base 64 the svg"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 1, "CLOSED": 10 },
      samplePRs: [
      ],
      sampleIssues: [
        { title: "`/bug-bounty`", url: "https://github.com/onmax/nimiq-identicons/issues/12", state: "CLOSED" },
        { title: "`/litepaper`", url: "https://github.com/onmax/nimiq-identicons/issues/11", state: "CLOSED" },
        { title: "`/oasis/integrate`", url: "https://github.com/onmax/nimiq-identicons/issues/10", state: "CLOSED" },
      ],
    },
    meta: { stars: 3, license: null, createdAt: "2024-10-24", updatedAt: "2025-08-12" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-icons",
    nameWithOwner: "onmax/nimiq-icons",
    role: "Creator & Maintainer",
    summary: "Focuses on general maintenance and feature development contributions. Recent commit: Added script to export figma icons. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-icons" },
      { label: "Live", url: "https://onmax.github.io/nimiq-icons/" },
    ],
    timeline: { start: "2023-01-17", end: "2023-11-06", duration: "9m", commitCount: 97 },
    stack: ["TypeScript"],
    highlights: [
      { label: "General maintenance", count: 15, examples: ["New icons (#292)", "New icons (#269)"] },
      { label: "Feature development", count: 10, examples: ["Added script to export figma icons", "Added category to workflow"] },
      { label: "Bug fixing", count: 9, examples: ["fixed dashboard", "Fixed icons"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 12, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 116 },
      samplePRs: [
        { title: "New icons", url: "https://github.com/onmax/nimiq-icons/pull/269", state: "MERGED" },
        { title: "New icons", url: "https://github.com/onmax/nimiq-icons/pull/256", state: "MERGED" },
        { title: "New icons", url: "https://github.com/onmax/nimiq-icons/pull/237", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "Add new icon", url: "https://github.com/onmax/nimiq-icons/issues/275", state: "CLOSED" },
        { title: "Add new icon", url: "https://github.com/onmax/nimiq-icons/issues/274", state: "CLOSED" },
        { title: "Add new icon", url: "https://github.com/onmax/nimiq-icons/issues/273", state: "CLOSED" },
      ],
    },
    meta: { stars: 1, license: null, createdAt: "2023-01-17", updatedAt: "2023-01-31" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-awesome",
    nameWithOwner: "onmax/nimiq-awesome",
    role: "Creator & Maintainer",
    summary: "A curated list of projects, applications and libraries built on top of the Nimiq blockchain",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-awesome" },
    ],
    timeline: { start: "2025-01-31", end: "2025-09-25", duration: "7m", commitCount: 75 },
    stack: ["TypeScript", "nimiq"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 27, examples: ["chore: add Task Master and Claude Code configuration", "chore: fix"] },
      { label: "Feature development", count: 22, examples: ["add nimiq starter resource", "feat: improve RPC servers with GitHub Alert and descriptive names"] },
      { label: "Documentation", count: 12, examples: ["simplify API.md documentation", "docs: add API Access section with usage examples"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 1 },
      issues: { "OPEN": 5, "CLOSED": 5 },
      samplePRs: [
        { title: "feat: add Pixels and nimworld apps by @paulghz", url: "https://github.com/onmax/nimiq-awesome/pull/12", state: "CLOSED" },
      ],
      sampleIssues: [
        { title: "Update preview nimiq pay and nimiq map", url: "https://github.com/onmax/nimiq-awesome/issues/11", state: "OPEN" },
        { title: "apps", url: "https://github.com/onmax/nimiq-awesome/issues/10", state: "CLOSED" },
        { title: "add MEXC", url: "https://github.com/onmax/nimiq-awesome/issues/9", state: "CLOSED" },
      ],
    },
    meta: { stars: 1, license: null, createdAt: "2025-01-31", updatedAt: "2025-09-25" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-changelog",
    nameWithOwner: "onmax/nimiq-changelog",
    role: "Creator & Maintainer",
    summary: "An application to track latest changes from multiple repositories from Nimiq",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-changelog" },
      { label: "Live", url: "https://nimiq-changelog.je-cf9.workers.dev/" },
    ],
    timeline: { start: "2025-09-11", end: "2025-09-29", duration: "under 1m", commitCount: 58 },
    stack: ["TypeScript", "nimiq"],
    highlights: [
      { label: "Feature development", count: 16, examples: ["feat: add multi-model LLM comparison system (#1)", "feat: send changelog as file attachment to Slack"] },
      { label: "Bug fixing", count: 9, examples: ["fix: replace jsdom with regex parsing for cloudflare workers compatibility", "fix: CI errors and remove dead code"] },
      { label: "Tooling & dependency upkeep", count: 6, examples: ["chore: fix test", "chore: removed dead code"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 1, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
        { title: "feat: add multi-model LLM comparison system", url: "https://github.com/onmax/nimiq-changelog/pull/1", state: "MERGED" },
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-09-11", updatedAt: "2025-09-29" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "ninja",
    nameWithOwner: "onmax/ninja",
    role: "Creator & Maintainer",
    summary: "Focuses on general maintenance and tooling & dependency upkeep contributions. Recent commit: chore: fixed build. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/ninja" },
    ],
    timeline: { start: "2024-10-12", end: "2024-11-06", duration: "under 1m", commitCount: 58 },
    stack: ["TypeScript"],
    highlights: [
      { label: "General maintenance", count: 18, examples: ["removed vectorize", "changed"] },
      { label: "Tooling & dependency upkeep", count: 13, examples: ["chore: fixed build", "chore: added caht"] },
      { label: "Feature development", count: 2, examples: ["chore(deployment): add workflow file", "adding search"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2024-10-12", updatedAt: "2024-11-06" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "tailwindcss-nimiq",
    nameWithOwner: "onmax/tailwindcss-nimiq",
    role: "Creator & Maintainer",
    summary: "A custom Tailwind CSS config with Nimiq styles",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/tailwindcss-nimiq" },
      { label: "Live", url: "https://onmax.github.io/tailwindcss-nimiq/" },
    ],
    timeline: { start: "2022-10-07", end: "2022-11-11", duration: "1m", commitCount: 49 },
    stack: ["JavaScript", "nimiq", "tailwindcss", "theme"],
    highlights: [
      { label: "General maintenance", count: 0, examples: ["[Add highlight summary]"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 2, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
        { title: "Quick opacity access", url: "https://github.com/onmax/tailwindcss-nimiq/issues/2", state: "OPEN" },
        { title: "Add color alias", url: "https://github.com/onmax/tailwindcss-nimiq/issues/1", state: "OPEN" },
      ],
    },
    meta: { stars: 3, license: null, createdAt: "2022-03-25", updatedAt: "2024-06-25" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-mcp",
    nameWithOwner: "onmax/nimiq-mcp",
    role: "Creator & Maintainer",
    summary: "A Model Context Protocol (MCP) server for interacting with the Nimiq blockchain.",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-mcp" },
      { label: "Live", url: "https://nimiq-mcp.je-cf9.workers.dev/" },
    ],
    timeline: { start: "2025-06-09", end: "2025-09-12", duration: "3m", commitCount: 47 },
    stack: ["TypeScript", "mcp", "nimiq"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 14, examples: ["update lockfile to pnpm 10 format", "chore: release v0.0.9"] },
      { label: "Feature development", count: 9, examples: ["add monthly health check with slack alerts", "Add new features and fix linting issues"] },
      { label: "Documentation", count: 7, examples: ["docs: restructure README to consolidate CLI and tool/resource details into tables for improved readability and organization", "docs: update README to remove outdated comparison details on network, performance, customization, and security for local installation"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 1, "OPEN": 0, "CLOSED": 1 },
      issues: { "OPEN": 0, "CLOSED": 2 },
      samplePRs: [
        { title: "Add comprehensive testing framework with Vitest and CI improvements", url: "https://github.com/onmax/nimiq-mcp/pull/4", state: "MERGED" },
        { title: "Add comprehensive testing framework with Vitest and CI improvements", url: "https://github.com/onmax/nimiq-mcp/pull/3", state: "CLOSED" },
      ],
      sampleIssues: [
        { title: "Price", url: "https://github.com/onmax/nimiq-mcp/issues/2", state: "CLOSED" },
        { title: "Supply", url: "https://github.com/onmax/nimiq-mcp/issues/1", state: "CLOSED" },
      ],
    },
    meta: { stars: 3, license: null, createdAt: "2025-06-09", updatedAt: "2025-09-12" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "lingai",
    nameWithOwner: "onmax/lingai",
    role: "Creator & Maintainer",
    summary: "Focuses on general maintenance and feature development contributions. Recent commit: added recap. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/lingai" },
      { label: "Live", url: "https://lingai.je-cf9.workers.dev/" },
    ],
    timeline: { start: "2025-06-04", end: "2025-06-15", duration: "under 1m", commitCount: 43 },
    stack: ["TypeScript"],
    highlights: [
      { label: "General maintenance", count: 38, examples: ["clean up", "compat flag"] },
      { label: "Feature development", count: 3, examples: ["added recap", "added title"] },
      { label: "Bug fixing", count: 2, examples: ["fix build", "fix audio"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-06-04", updatedAt: "2025-06-15" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "unocss-preset-fluid-sizing",
    nameWithOwner: "onmax/unocss-preset-fluid-sizing",
    role: "Creator & Maintainer",
    summary: "[Archived] UnoCSS preset for fluid sizing with UnoCSS philosophy in mind.",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/unocss-preset-fluid-sizing" },
      { label: "Live", url: "https://onmax.github.io/unocss-preset-onmax/unocss-preset-fluid-sizing" },
    ],
    timeline: { start: "2025-01-17", end: "2025-05-04", duration: "3m", commitCount: 40 },
    stack: ["TypeScript", "css", "fluid-typography", "unocss", "unocss-preset"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 31, examples: ["chore: release v0.0.17", "chore: updated dependencies"] },
      { label: "Feature development", count: 4, examples: ["chore!: added archived notification", "feat: add test cases and configuration for fluid text sizing"] },
      { label: "Bug fixing", count: 3, examples: ["fix: css vars", "fix: ts...."] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 3, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
        { title: "Allow text=\"f-xs\" in attributify", url: "https://github.com/onmax/unocss-preset-fluid-sizing/issues/3", state: "OPEN" },
        { title: "missing `ring-<number>`", url: "https://github.com/onmax/unocss-preset-fluid-sizing/issues/2", state: "OPEN" },
        { title: "flex=\"~ f-gap-xl\"", url: "https://github.com/onmax/unocss-preset-fluid-sizing/issues/1", state: "OPEN" },
      ],
    },
    meta: { stars: 5, license: null, createdAt: "2025-01-17", updatedAt: "2025-05-10" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-starter",
    nameWithOwner: "onmax/nimiq-starter",
    role: "Creator & Maintainer",
    summary: "Mulitple starter templates for integrating Nimiq web client",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-starter" },
      { label: "Live", url: "https://nimiq.dev" },
    ],
    timeline: { start: "2025-09-24", end: "2025-09-29", duration: "under 1m", commitCount: 38 },
    stack: ["JavaScript"],
    highlights: [
      { label: "Bug fixing", count: 12, examples: ["Fix Cloudflare wasm bundling for Nimiq", "Fix Cloudflare worker wasm bootstrap"] },
      { label: "Tooling & dependency upkeep", count: 9, examples: ["chore: renamed name cloudflare", "chore: simplify vue"] },
      { label: "Documentation", count: 6, examples: ["Document live demos for web starters", "docs: add AGENTS.md symlink to CLAUDE.md"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 3, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
        { title: "feat: Add Cloudflare D1 starter with Nimiq integration", url: "https://github.com/onmax/nimiq-starter/pull/3", state: "MERGED" },
        { title: "feat: Add React TypeScript starter", url: "https://github.com/onmax/nimiq-starter/pull/2", state: "MERGED" },
        { title: "feat: Add Next.js starter with Nimiq blockchain integration", url: "https://github.com/onmax/nimiq-starter/pull/1", state: "MERGED" },
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-09-24", updatedAt: "2025-09-29" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "issue-form-parser",
    nameWithOwner: "onmax/issue-form-parser",
    role: "Creator & Maintainer",
    summary: "Convert GitHub Form Issues into JSON objects with this simple Action.",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/issue-form-parser" },
      { label: "Live", url: "https://github.com/marketplace/actions/issue-form-parser" },
    ],
    timeline: { start: "2023-01-21", end: "2025-01-19", duration: "2y", commitCount: 29 },
    stack: ["TypeScript", "github-actions", "issue-forms", "parser", "json"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 8, examples: ["chore: semver", "chore: updated dependencies"] },
      { label: "Feature development", count: 4, examples: ["Build", "Added support for checkboxes and dropdowns"] },
      { label: "Documentation", count: 2, examples: ["code and docs more robust", "updated readme"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 2, "CLOSED": 4 },
      samplePRs: [
      ],
      sampleIssues: [
        { title: "Issue form template", url: "https://github.com/onmax/issue-form-parser/issues/17", state: "OPEN" },
        { title: "Issue form template", url: "https://github.com/onmax/issue-form-parser/issues/16", state: "CLOSED" },
        { title: "Issue form template", url: "https://github.com/onmax/issue-form-parser/issues/15", state: "CLOSED" },
      ],
    },
    meta: { stars: 3, license: null, createdAt: "2023-01-21", updatedAt: "2025-01-19" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "unocss-preset-gradient-fn",
    nameWithOwner: "onmax/unocss-preset-gradient-fn",
    role: "Creator & Maintainer",
    summary: "Focuses on tooling & dependency upkeep and documentation contributions. Recent commit: docs: update README and documentation links after repository migration. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/unocss-preset-gradient-fn" },
      { label: "Live", url: "https://onmax.github.io/unocss-preset-onmax/unocss-preset-easing-gradient/" },
    ],
    timeline: { start: "2024-11-06", end: "2025-05-04", duration: "5m", commitCount: 28 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 22, examples: ["chore: release v0.0.1-beta-1.0", "chore: removed peerDependencies"] },
      { label: "Documentation", count: 3, examples: ["docs: update README and documentation links after repository migration", "docs: fix links"] },
      { label: "General maintenance", count: 2, examples: ["version", "first commit"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 1 },
      samplePRs: [
      ],
      sampleIssues: [
        { title: "use color.js", url: "https://github.com/onmax/unocss-preset-gradient-fn/issues/1", state: "CLOSED" },
      ],
    },
    meta: { stars: 4, license: null, createdAt: "2024-11-06", updatedAt: "2025-05-04" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "albatross-liveview",
    nameWithOwner: "onmax/albatross-liveview",
    role: "Creator & Maintainer",
    summary: "Focuses on tooling & dependency upkeep and general maintenance contributions. Recent commit: fixes. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/albatross-liveview" },
      { label: "Live", url: "https://albatross-liveview.nuxt.dev/" },
    ],
    timeline: { start: "2024-09-01", end: "2024-09-05", duration: "under 1m", commitCount: 27 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 9, examples: ["chore: create multiple streams", "chore: refactor some backend"] },
      { label: "General maintenance", count: 5, examples: ["improvmetns", "enable websocket on server side"] },
      { label: "Feature development", count: 4, examples: ["feat: added stats panel", "feat: added chain animation"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2024-09-01", updatedAt: "2024-09-05" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-onmax-vue-template",
    nameWithOwner: "onmax/nimiq-onmax-vue-template",
    role: "Creator & Maintainer",
    summary: "This template should help you get started developing with Nimiq in Vue 3. Highly opinionated.",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-onmax-vue-template" },
      { label: "Live", url: "https://onmax.github.io/nimiq-vue-template/" },
    ],
    timeline: { start: "2024-04-04", end: "2024-08-31", duration: "4m", commitCount: 27 },
    stack: ["Vue", "nimiq", "vue-3"],
    highlights: [
      { label: "Feature development", count: 9, examples: ["added some vite plugins", "added deployment"] },
      { label: "Tooling & dependency upkeep", count: 9, examples: ["chore: updated dependencies", "updated dependencies"] },
      { label: "General maintenance", count: 3, examples: ["Removed temporarily checked", "removed unused item"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 2, license: null, createdAt: "2024-04-04", updatedAt: "2024-08-31" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "onmax",
    nameWithOwner: "onmax/onmax",
    role: "Creator & Maintainer",
    summary: "Focuses on tooling & dependency upkeep and bug fixing contributions. Recent commit: feat: added composables post. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/onmax" },
      { label: "Live", url: "https://onmax.github.io/onmax/" },
    ],
    timeline: { start: "2023-03-23", end: "2025-06-18", duration: "2y 3m", commitCount: 27 },
    stack: ["Astro"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 8, examples: ["updated nimiq-css class", "updated content"] },
      { label: "Bug fixing", count: 6, examples: ["fixed link", "fix paths"] },
      { label: "General maintenance", count: 6, examples: ["publish nimiq icons", "finished blog posts"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2021-08-12", updatedAt: "2025-06-18" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-nuxt-template",
    nameWithOwner: "onmax/nimiq-nuxt-template",
    role: "Creator & Maintainer",
    summary: "This template should help you get started developing with Nimiq in Nuxt 3. Highly opinionated.",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-nuxt-template" },
      { label: "Live", url: "https://nuxt-template.nuxt.dev" },
    ],
    timeline: { start: "2024-05-14", end: "2024-11-22", duration: "6m", commitCount: 23 },
    stack: ["Vue", "nimiq", "nuxt"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 11, examples: ["chore: client only", "chore: update dependencies"] },
      { label: "General maintenance", count: 5, examples: ["oopsie", "work around for nimiq core"] },
      { label: "Bug fixing", count: 3, examples: ["fix url", "fixed issues and installed dependencies"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 3 },
      samplePRs: [
      ],
      sampleIssues: [
        { title: "Add vue use autoimport", url: "https://github.com/onmax/nimiq-nuxt-template/issues/3", state: "CLOSED" },
        { title: "Add @nuxt/image", url: "https://github.com/onmax/nimiq-nuxt-template/issues/2", state: "CLOSED" },
        { title: "Add transformer", url: "https://github.com/onmax/nimiq-nuxt-template/issues/1", state: "CLOSED" },
      ],
    },
    meta: { stars: 1, license: null, createdAt: "2024-05-14", updatedAt: "2025-06-21" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nuxt-safe-runtime-config",
    nameWithOwner: "onmax/nuxt-safe-runtime-config",
    role: "Creator & Maintainer",
    summary: "Validate Nuxt runtime config at build time using Zod, Valibot, ArkType... any Standard Schema library",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nuxt-safe-runtime-config" },
    ],
    timeline: { start: "2025-06-04", end: "2025-06-05", duration: "under 1m", commitCount: 23 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 7, examples: ["chore: release v0.0.3", "chore: linter"] },
      { label: "Documentation", count: 5, examples: ["docs: added RFC thread", "docs: added logo"] },
      { label: "Bug fixing", count: 2, examples: ["fix: add optional chaining for schema validation check", "fix: tests work"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 8, license: null, createdAt: "2025-06-04", updatedAt: "2025-08-03" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "cpnow",
    nameWithOwner: "onmax/cpnow",
    role: "Creator & Maintainer",
    summary: "Focuses on tooling & dependency upkeep and documentation contributions. Recent commit: chore: release v0.0.6. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/cpnow" },
    ],
    timeline: { start: "2025-02-03", end: "2025-06-05", duration: "4m", commitCount: 20 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 15, examples: ["chore: release v0.0.6", "chore: updated dependencies"] },
      { label: "Documentation", count: 2, examples: ["docs: removed license", "docs: added readme"] },
      { label: "Feature development", count: 1, examples: ["feat: add GitHub API token support for authentication and update README"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 2 },
      samplePRs: [
      ],
      sampleIssues: [
        { title: "handles assets that are not text-based", url: "https://github.com/onmax/cpnow/issues/2", state: "CLOSED" },
        { title: "allow files to be read", url: "https://github.com/onmax/cpnow/issues/1", state: "CLOSED" },
      ],
    },
    meta: { stars: 1, license: null, createdAt: "2025-02-03", updatedAt: "2025-06-05" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-email-signatures",
    nameWithOwner: "onmax/nimiq-email-signatures",
    role: "Creator & Maintainer",
    summary: "A builder for your email signature.",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-email-signatures" },
      { label: "Live", url: "https://frabjous-pothos-386060.netlify.app/" },
    ],
    timeline: { start: "2023-12-19", end: "2024-01-26", duration: "1m", commitCount: 19 },
    stack: ["Vue", "email-signature"],
    highlights: [
      { label: "General maintenance", count: 6, examples: ["vertically align", "improvments"] },
      { label: "Tooling & dependency upkeep", count: 5, examples: ["updates dep", " Update CSS colors and styles, package versions, and UI components"] },
      { label: "Bug fixing", count: 4, examples: ["fixed colors in email", "fixed vite warning"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2023-12-19", updatedAt: "2023-12-19" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-playground",
    nameWithOwner: "onmax/nimiq-playground",
    role: "Creator & Maintainer",
    summary: "Focuses on tooling & dependency upkeep and feature development contributions. Recent commit: Merge pull request #1 from Albermonte/albermonte/deps. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-playground" },
      { label: "Live", url: "https://nimiq-playground.pages.dev/" },
    ],
    timeline: { start: "2024-05-11", end: "2024-12-07", duration: "7m", commitCount: 18 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 4, examples: ["Merge pull request #1 from Albermonte/albermonte/deps", "chore: improve sharing"] },
      { label: "Feature development", count: 3, examples: ["added tutorials", "added dark mode switch"] },
      { label: "Bug fixing", count: 3, examples: ["fixes", "fix sharing"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2024-05-11", updatedAt: "2025-01-23" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "onmax-nuxt-template",
    nameWithOwner: "onmax/onmax-nuxt-template",
    role: "Creator & Maintainer",
    summary: "Focuses on tooling & dependency upkeep and feature development contributions. Recent commit: feat: chats. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/onmax-nuxt-template" },
    ],
    timeline: { start: "2025-01-25", end: "2025-01-28", duration: "under 1m", commitCount: 17 },
    stack: ["Vue"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 14, examples: ["chore: enable ai", "chore: fixed auth"] },
      { label: "Feature development", count: 1, examples: ["feat: chats"] },
      { label: "Bug fixing", count: 1, examples: ["fix: build"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-01-25", updatedAt: "2025-01-28" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-core-nuxthub-repro",
    nameWithOwner: "onmax/nimiq-core-nuxthub-repro",
    role: "Creator & Maintainer",
    summary: "Focuses on general maintenance and testing & quality contributions. Recent commit: chore: added hook to copy wasm. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-core-nuxthub-repro" },
    ],
    timeline: { start: "2025-02-11", end: "2025-02-12", duration: "under 1m", commitCount: 16 },
    stack: ["TypeScript"],
    highlights: [
      { label: "General maintenance", count: 7, examples: ["t", "d"] },
      { label: "Testing & quality", count: 2, examples: ["test", "test"] },
      { label: "Feature development", count: 1, examples: ["added nimiq/core"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-02-11", updatedAt: "2025-02-12" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-rolldown",
    nameWithOwner: "onmax/nimiq-rolldown",
    role: "Creator & Maintainer",
    summary: "Focuses on general maintenance and feature development contributions. Recent commit: readme. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-rolldown" },
    ],
    timeline: { start: "2025-09-01", end: "2025-09-03", duration: "under 1m", commitCount: 16 },
    stack: ["Vue"],
    highlights: [
      { label: "General maintenance", count: 6, examples: ["NETOWKRS NAMES", "type"] },
      { label: "Feature development", count: 4, examples: ["build issue rolldown", "Keep only vite-plugin-wasm for Nimiq WASM support"] },
      { label: "Bug fixing", count: 2, examples: ["Fix TypeScript errors: use union types instead of enum", "Fix GitHub Actions: install pnpm before Node setup"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 1, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
        { title: "`vite:latests` works", url: "https://github.com/onmax/nimiq-rolldown/pull/1", state: "OPEN" },
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-09-01", updatedAt: "2025-09-03" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "joxi",
    nameWithOwner: "onmax/joxi",
    role: "Creator & Maintainer",
    summary: "An automatic personal finance tracker for your banks and crypto. All your finance data in Notion.",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/joxi" },
    ],
    timeline: { start: "2022-10-11", end: "2022-11-20", duration: "1m", commitCount: 15 },
    stack: ["TypeScript", "coinbase-api", "cronjob", "finance-tracker", "github-action", "nordigen", "notion"],
    highlights: [
      { label: "Feature development", count: 1, examples: ["added checks before reduce and added warn"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 13, license: null, createdAt: "2022-09-04", updatedAt: "2025-06-14" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "unocss-preset-scale-px",
    nameWithOwner: "onmax/unocss-preset-scale-px",
    role: "Creator & Maintainer",
    summary: "[Archived] A UnoCSS preset that maps utility numbers directly to pixel values (e.g., `p-4` → `0.25rem(4px)`).",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/unocss-preset-scale-px" },
      { label: "Live", url: "https://onmax.github.io/unocss-preset-onmax/unocss-preset-scale-px" },
    ],
    timeline: { start: "2025-01-14", end: "2025-05-04", duration: "3m", commitCount: 15 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 6, examples: ["chore: release v0.0.2", "chore: added tests"] },
      { label: "Feature development", count: 1, examples: ["chore!: added notification"] },
      { label: "Documentation", count: 1, examples: ["docs: clarify readme"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 1, license: null, createdAt: "2025-01-14", updatedAt: "2025-05-04" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-frankenstein",
    nameWithOwner: "onmax/nimiq-frankenstein",
    role: "Creator & Maintainer",
    summary: "Focuses on tooling & dependency upkeep contributions. Recent commit: chore: added project baseline. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-frankenstein" },
      { label: "Live", url: "https://onmax.github.io/nimiq-frankenstein/" },
    ],
    timeline: { start: "2025-02-17", end: "2025-02-20", duration: "under 1m", commitCount: 10 },
    stack: ["Vue"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 1, examples: ["chore: added project baseline"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-02-17", updatedAt: "2025-02-20" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "render-markdown-it-tokens",
    nameWithOwner: "onmax/render-markdown-it-tokens",
    role: "Creator & Maintainer",
    summary: "Focuses on tooling & dependency upkeep and feature development contributions. Recent commit: chore: release v0.0.4. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/render-markdown-it-tokens" },
    ],
    timeline: { start: "2025-02-28", end: "2025-02-28", duration: "under 1m", commitCount: 10 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 6, examples: ["chore: release v0.0.4", "chore: release v0.0.3"] },
      { label: "Feature development", count: 1, examples: ["feat: add HTML block rendering and fallback for unknown token types"] },
      { label: "Bug fixing", count: 1, examples: ["fix: streamline token rendering logic in renderMarkdownItTokens function"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-02-28", updatedAt: "2025-02-28" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "valibot-to-ts",
    nameWithOwner: "onmax/valibot-to-ts",
    role: "Creator & Maintainer",
    summary: "Valibot Schema -> JSON Schema -> TS",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/valibot-to-ts" },
    ],
    timeline: { start: "2025-01-28", end: "2025-01-28", duration: "under 1m", commitCount: 9 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Documentation", count: 1, examples: ["docs: removed section"] },
      { label: "Tooling & dependency upkeep", count: 1, examples: ["chore: store schemas"] },
      { label: "General maintenance", count: 1, examples: ["first commit"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 3, license: null, createdAt: "2025-01-28", updatedAt: "2025-06-04" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "css4ify",
    nameWithOwner: "onmax/css4ify",
    role: "Creator & Maintainer",
    summary: "Converts CSS to JSON",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/css4ify" },
    ],
    timeline: { start: "2024-03-04", end: "2024-03-05", duration: "under 1m", commitCount: 8 },
    stack: ["TypeScript", "css-to-js", "csstree", "css-nesting"],
    highlights: [
      { label: "Feature development", count: 4, examples: ["added parser from json to css", "added build"] },
      { label: "Documentation", count: 2, examples: ["updated readme", "updated readme"] },
      { label: "Tooling & dependency upkeep", count: 1, examples: ["updated version"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 1, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
        { title: "Merging multiple definitions into one ", url: "https://github.com/onmax/css4ify/issues/1", state: "OPEN" },
      ],
    },
    meta: { stars: 1, license: null, createdAt: "2024-03-04", updatedAt: "2025-01-18" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "eslint-plugin-pnpm-catalog",
    nameWithOwner: "onmax/eslint-plugin-pnpm-catalog",
    role: "Creator & Maintainer",
    summary: "ESLint plugin that enforces the use of named catalogs in pnpm workspaces",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/eslint-plugin-pnpm-catalog" },
    ],
    timeline: { start: "2025-05-31", end: "2025-06-05", duration: "under 1m", commitCount: 8 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 3, examples: ["chore: release v0.0.2", "chore: updated lock"] },
      { label: "Feature development", count: 1, examples: ["feat: enhance eslint-plugin-pnpm-catalog with new rules and configurations"] },
      { label: "Bug fixing", count: 1, examples: ["fix: correct message wording"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 3, license: null, createdAt: "2025-05-31", updatedAt: "2025-06-15" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-roadmap",
    nameWithOwner: "onmax/nimiq-roadmap",
    role: "Creator & Maintainer",
    summary: "Focuses on general maintenance and feature development contributions. Recent commit: makign progress in layout. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-roadmap" },
    ],
    timeline: { start: "2024-04-16", end: "2024-04-29", duration: "under 1m", commitCount: 8 },
    stack: ["Vue"],
    highlights: [
      { label: "General maintenance", count: 5, examples: ["makign progress in layout", "improvments"] },
      { label: "Feature development", count: 1, examples: ["added deployment"] },
      { label: "Bug fixing", count: 1, examples: ["fixed buikd"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2024-04-16", updatedAt: "2024-04-29" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-ticket",
    nameWithOwner: "onmax/nimiq-ticket",
    role: "Creator & Maintainer",
    summary: "Focuses on general maintenance and feature development contributions. Recent commit: added basic styles. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-ticket" },
    ],
    timeline: { start: "2024-04-23", end: "2024-04-25", duration: "under 1m", commitCount: 8 },
    stack: ["Vue"],
    highlights: [
      { label: "General maintenance", count: 5, examples: ["ups", "spaces"] },
      { label: "Feature development", count: 2, examples: ["added basic styles", "added login and config"] },
      { label: "Tooling & dependency upkeep", count: 1, examples: ["updated config"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2024-04-23", updatedAt: "2024-04-25" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nimiq-validator-trust-score-old",
    nameWithOwner: "onmax/nimiq-validator-trust-score-old",
    role: "Creator & Maintainer",
    summary: "A module to calculate Nimiq's Validator Trust Score",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nimiq-validator-trust-score-old" },
    ],
    timeline: { start: "2023-03-21", end: "2023-05-18", duration: "1m", commitCount: 8 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Feature development", count: 3, examples: ["add .env to docker", "added initial commit"] },
      { label: "General maintenance", count: 2, examples: ["changes", "first commit"] },
      { label: "Tooling & dependency upkeep", count: 1, examples: ["updated ftld"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 1, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
        { title: "Track deactivation when validator has been misbehaving. There is no tx for that", url: "https://github.com/onmax/nimiq-validator-trust-score-old/issues/1", state: "OPEN" },
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2023-03-21", updatedAt: "2024-10-17" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "open-rpc-msw",
    nameWithOwner: "onmax/open-rpc-msw",
    role: "Creator & Maintainer",
    summary: "Repro for issue",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/open-rpc-msw" },
      { label: "Live", url: "https://github.com/mswjs/msw/discussions/2414" },
    ],
    timeline: { start: "2025-02-17", end: "2025-02-22", duration: "under 1m", commitCount: 8 },
    stack: ["TypeScript"],
    highlights: [
      { label: "General maintenance", count: 3, examples: ["setup", "minimal setup"] },
      { label: "Documentation", count: 2, examples: ["updated readme", "updated readme"] },
      { label: "Tooling & dependency upkeep", count: 2, examples: ["chore: updated handshake", "chore: patch WebSocket"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-02-17", updatedAt: "2025-02-22" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "joxi-github-action",
    nameWithOwner: "onmax/joxi-github-action",
    role: "Creator & Maintainer",
    summary: "A GitHub action for joxi: An automatic personal finance tracker for your banks and crypto. All your finance data in Notion.",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/joxi-github-action" },
    ],
    timeline: { start: "2022-10-14", end: "2022-11-18", duration: "1m", commitCount: 6 },
    stack: ["Dockerfile", "coinbase-api", "finance-tracker", "github-action", "nordigen", "cronjob", "notion"],
    highlights: [
      { label: "General maintenance", count: 0, examples: ["[Add highlight summary]"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 4, license: null, createdAt: "2022-10-14", updatedAt: "2024-10-15" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "albatross-util-wasm",
    nameWithOwner: "onmax/albatross-util-wasm",
    role: "Creator & Maintainer",
    summary: "Focuses on tooling & dependency upkeep and general maintenance contributions. Recent commit: cargo.lock. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/albatross-util-wasm" },
      { label: "Live", url: "https://www.npmjs.com/package/albatross-util-wasm" },
    ],
    timeline: { start: "2023-03-27", end: "2023-05-15", duration: "1m", commitCount: 5 },
    stack: ["Rust"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 2, examples: ["updated wasm", "update cargo toml"] },
      { label: "General maintenance", count: 2, examples: ["cargo.lock", "First commit"] },
      { label: "Feature development", count: 1, examples: ["added parser for OutgoingStakingTransactionProof"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2023-03-28", updatedAt: "2023-03-28" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nitro-nimiq-core-wasm",
    nameWithOwner: "onmax/nitro-nimiq-core-wasm",
    role: "Creator & Maintainer",
    summary: "Repro for issue in Nitro",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nitro-nimiq-core-wasm" },
      { label: "Live", url: "https://github.com/nitrojs/nitro/issues/3089" },
    ],
    timeline: { start: "2025-02-12", end: "2025-02-13", duration: "under 1m", commitCount: 5 },
    stack: ["TypeScript"],
    highlights: [
      { label: "General maintenance", count: 3, examples: ["clean up", "clean up"] },
      { label: "Feature development", count: 1, examples: ["added await mod() to attempt 2"] },
      { label: "Tooling & dependency upkeep", count: 1, examples: ["chore: treat nimiq/core as inline"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-02-12", updatedAt: "2025-02-17" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "nuxt-onmax-template-old",
    nameWithOwner: "onmax/nuxt-onmax-template-old",
    role: "Creator & Maintainer",
    summary: "Focuses on tooling & dependency upkeep contributions. Recent commit: chore: added auth. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/nuxt-onmax-template-old" },
    ],
    timeline: { start: "2025-01-25", end: "2025-01-25", duration: "under 1m", commitCount: 5 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 5, examples: ["chore: added auth", "chore: database"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-01-25", updatedAt: "2025-01-25" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "personal",
    owner: "onmax",
    name: "web-container-nimiq",
    nameWithOwner: "onmax/web-container-nimiq",
    role: "Creator & Maintainer",
    summary: "Focuses on general maintenance and documentation contributions. Recent commit: a. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/onmax/web-container-nimiq" },
    ],
    timeline: { start: "2025-06-17", end: "2025-06-17", duration: "under 1m", commitCount: 5 },
    stack: ["JavaScript"],
    highlights: [
      { label: "General maintenance", count: 3, examples: ["a", "a"] },
      { label: "Documentation", count: 1, examples: ["docs"] },
      { label: "Architecture & refactors", count: 1, examples: ["Refactor Nimiq test process: replace buttons, streamline operations, and enhance logging"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-06-17", updatedAt: "2025-06-17" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "crypto-map",
    nameWithOwner: "nimiq/crypto-map",
    role: "Core Maintainer & Frontend Engineer (Nimiq)",
    summary: "The Crypto Map by Nimiq. Explore the world and find places to spend your crypto.",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/crypto-map" },
      { label: "Live", url: "https://map.nimiq.com" },
    ],
    timeline: { start: "2022-10-10", end: "2025-09-18", duration: "2y 11m", commitCount: 1060 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 66, examples: ["chore: lint and typecheck", "chore: updated icons path"] },
      { label: "Bug fixing", count: 47, examples: ["fix: ui class", "fixes"] },
      { label: "General maintenance", count: 42, examples: ["new endpoint", "return parsed locations"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 8, "OPEN": 0, "CLOSED": 1 },
      issues: { "OPEN": 4, "CLOSED": 0 },
      samplePRs: [
        { title: "Matheo/wip", url: "https://github.com/nimiq/crypto-map/pull/4", state: "MERGED" },
        { title: "Matheo/wip", url: "https://github.com/nimiq/crypto-map/pull/3", state: "MERGED" },
        { title: "Forms", url: "https://github.com/nimiq/crypto-map/pull/1", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "Change default map", url: "https://github.com/nimiq/crypto-map/issues/18", state: "OPEN" },
        { title: "Add dark uri", url: "https://github.com/nimiq/crypto-map/issues/17", state: "OPEN" },
        { title: "Add cryptocity info ", url: "https://github.com/nimiq/crypto-map/issues/12", state: "OPEN" },
      ],
    },
    meta: { stars: 6, license: null, createdAt: "2022-07-13", updatedAt: "2025-09-18" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "developer-center",
    nameWithOwner: "nimiq/developer-center",
    role: "Core Maintainer & Frontend Engineer (Nimiq)",
    summary: "The Official documentation for the Nimiq ecosystem.",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/developer-center" },
      { label: "Live", url: "https://nimiq.com/developers" },
    ],
    timeline: { start: "2023-10-23", end: "2025-06-07", duration: "1y 7m", commitCount: 755 },
    stack: ["Vue"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 75, examples: ["chore: updated vitepress llms", "chore: update TypeDoc and related dependencies, adjust build command and TypeScript configuration"] },
      { label: "General maintenance", count: 48, examples: ["Merge branch 'main' into ines-vts", "Merge pull request #86 from nimiq/stefan/align-client-example-toml"] },
      { label: "Bug fixing", count: 36, examples: ["fix: display icons", "fix: css styles"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 14, "OPEN": 2, "CLOSED": 5 },
      issues: { "OPEN": 11, "CLOSED": 38 },
      samplePRs: [
        { title: "chore: updated dependencies and linter", url: "https://github.com/nimiq/developer-center/pull/55", state: "MERGED" },
        { title: "Implementation of new Sidebar logic", url: "https://github.com/nimiq/developer-center/pull/32", state: "CLOSED" },
        { title: "Validator Score", url: "https://github.com/nimiq/developer-center/pull/21", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "Remove layers.css", url: "https://github.com/nimiq/developer-center/issues/47", state: "CLOSED" },
        { title: "Links in Community menu item —> Blog / Podcast missing target _blank", url: "https://github.com/nimiq/developer-center/issues/38", state: "CLOSED" },
        { title: "Wrong z-index in modal in icon detail", url: "https://github.com/nimiq/developer-center/issues/37", state: "CLOSED" },
      ],
    },
    meta: { stars: 2, license: null, createdAt: "2024-02-08", updatedAt: "2025-06-07" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "nimiq-website",
    nameWithOwner: "nimiq/nimiq-website",
    role: "Core Maintainer & Frontend Engineer (Nimiq)",
    summary: "The source code for the Nimiq website.",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/nimiq-website" },
      { label: "Live", url: "https://www.nimiq.com" },
    ],
    timeline: { start: "2024-09-05", end: "2025-09-15", duration: "1y", commitCount: 689 },
    stack: ["Vue", "nimiq", "nuxt"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 113, examples: ["chore: switch Matomo to mainnet (siteId: 2)", "chore: update ssrWidth for mobile media query in WalletPlayground"] },
      { label: "Feature development", count: 30, examples: ["refactor(Blockchain.vue): optimize animation logic and improve performance by using direct DOM manipulation", "fix(LogosGrid): add width class"] },
      { label: "Architecture & refactors", count: 25, examples: ["refactor: reorganize Prismic image utilities and update message handling in Wallet components", "refactor: update WebSocket handler for Albatross liveview and remove unused liveview types"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 39, "OPEN": 0, "CLOSED": 10 },
      issues: { "OPEN": 28, "CLOSED": 72 },
      samplePRs: [
        { title: "chore: update Claude workflows for improved review process", url: "https://github.com/nimiq/nimiq-website/pull/191", state: "MERGED" },
        { title: "Claude PR Assistant workflow", url: "https://github.com/nimiq/nimiq-website/pull/190", state: "MERGED" },
        { title: "New internal dynamic", url: "https://github.com/nimiq/nimiq-website/pull/178", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "provenance-action", url: "https://github.com/nimiq/nimiq-website/issues/199", state: "OPEN" },
        { title: "Overflow Y missing scroll", url: "https://github.com/nimiq/nimiq-website/issues/198", state: "OPEN" },
        { title: "Iframe has not the right side", url: "https://github.com/nimiq/nimiq-website/issues/196", state: "OPEN" },
      ],
    },
    meta: { stars: 3, license: null, createdAt: "2024-09-05", updatedAt: "2025-09-15" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "validators-api",
    nameWithOwner: "nimiq/validators-api",
    role: "Core Maintainer & Frontend Engineer (Nimiq)",
    summary: "Focuses on tooling & dependency upkeep and feature development contributions. Recent commit: Merge pull request #115 from nimiq/dev. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/validators-api" },
      { label: "Live", url: "https://validators-api-mainnet.pages.dev" },
    ],
    timeline: { start: "2024-05-16", end: "2025-07-24", duration: "1y 2m", commitCount: 519 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 116, examples: ["chore: remove pnpm-lock.yaml file as it is no longer needed", "chore: remove unused import of validatorsSchema in JSON validation script"] },
      { label: "Feature development", count: 41, examples: ["feat: integrate Slack notifications for sync events and enhance error handling in API endpoints", "feat: integrate Slack notifications for sync events and enhance error handling in API endpoints"] },
      { label: "Bug fixing", count: 13, examples: ["fix: initialize sorting state and enhance header click functionality in ValidatorsTable", "Merge pull request #112 from nimiq/onmax-patch-1"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 23, "OPEN": 0, "CLOSED": 3 },
      issues: { "OPEN": 11, "CLOSED": 19 },
      samplePRs: [
        { title: "Retrieve size from ended epochs", url: "https://github.com/nimiq/validators-api/pull/4", state: "MERGED" },
        { title: "Onmax/new validators just in current epoch", url: "https://github.com/nimiq/validators-api/pull/3", state: "MERGED" },
        { title: "feat: enhance grid utilities and improve validator table functionality", url: "https://github.com/nimiq/validators-api/pull/115", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "Epoch size", url: "https://github.com/nimiq/validators-api/issues/2", state: "CLOSED" },
        { title: "incorrect window size", url: "https://github.com/nimiq/validators-api/issues/1", state: "CLOSED" },
        { title: "Run `nr release` for v1", url: "https://github.com/nimiq/validators-api/issues/110", state: "OPEN" },
      ],
    },
    meta: { stars: 3, license: null, createdAt: "2024-05-16", updatedAt: "2025-08-04" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "feedback",
    nameWithOwner: "nimiq/feedback",
    role: "Senior Contributor (Nimiq)",
    summary: "Focuses on tooling & dependency upkeep and feature development contributions. Recent commit: fix: add missing vue-tsc dependency. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/feedback" },
      { label: "Live", url: "https://nimiq-feedback.je-cf9.workers.dev/" },
    ],
    timeline: { start: "2025-05-14", end: "2025-09-24", duration: "4m", commitCount: 135 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 59, examples: ["chore: updated dependences", "chore: downgrade nuxt 4"] },
      { label: "Feature development", count: 23, examples: ["Trigger CI build~", "Trigger CI build"] },
      { label: "Bug fixing", count: 18, examples: ["fix: add missing vue-tsc dependency", "fix: css issues"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 3, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 70 },
      samplePRs: [
        { title: "feat: Move playground to backend and add documentation", url: "https://github.com/nimiq/feedback/pull/60", state: "MERGED" },
        { title: "chore: extract modal", url: "https://github.com/nimiq/feedback/pull/50", state: "MERGED" },
        { title: "Fix: Resolve TypeScript errors and improve type safety", url: "https://github.com/nimiq/feedback/pull/13", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "[nimiq-pay] - Bug report", url: "https://github.com/nimiq/feedback/issues/73", state: "CLOSED" },
        { title: "[nimiq-pay] - Bug report", url: "https://github.com/nimiq/feedback/issues/72", state: "CLOSED" },
        { title: "[nimiq-pay] - Bug report", url: "https://github.com/nimiq/feedback/issues/71", state: "CLOSED" },
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-05-14", updatedAt: "2025-09-24" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "wallet",
    nameWithOwner: "nimiq/wallet",
    role: "Senior Contributor (Nimiq)",
    summary: "Browser Wallet for the Nimiq cryptocurrency",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/wallet" },
      { label: "Live", url: "https://wallet.nimiq.com" },
    ],
    timeline: { start: "2022-12-15", end: "2025-05-08", duration: "2y 5m", commitCount: 55 },
    stack: ["Vue"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 20, examples: ["chore: replace MEXC PNG logo with SVG version", "chore: update vue-router to be able to use `addRoute`"] },
      { label: "General maintenance", count: 16, examples: ["Disable buttons if active currency is NIM and disable network flag is active", "Remove extra width in ContactShortcut"] },
      { label: "Feature development", count: 14, examples: ["feat: Updated logic in sidebar to toggle sell feature", "chore(vue3): added locale to useI18n"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 7, "OPEN": 4, "CLOSED": 6 },
      issues: { "OPEN": 4, "CLOSED": 1 },
      samplePRs: [
        { title: "fix(TransactionListItem): don't cut out svg", url: "https://github.com/nimiq/wallet/pull/179", state: "MERGED" },
        { title: "Onmax/fix btc logo", url: "https://github.com/nimiq/wallet/pull/178", state: "CLOSED" },
        { title: "Add support for SINPE Movil", url: "https://github.com/nimiq/wallet/pull/163", state: "CLOSED" },
      ],
      sampleIssues: [
        { title: "Address in the Validator modal", url: "https://github.com/nimiq/wallet/issues/279", state: "OPEN" },
        { title: "Migration to Vue 3 Overview", url: "https://github.com/nimiq/wallet/issues/264", state: "OPEN" },
        { title: "Adding `LICENSE` file", url: "https://github.com/nimiq/wallet/issues/260", state: "OPEN" },
      ],
    },
    meta: { stars: 51, license: null, createdAt: "2020-06-04", updatedAt: "2025-09-17" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "tutorial",
    nameWithOwner: "nimiq/tutorial",
    role: "Senior Contributor (Nimiq)",
    summary: "Learn how to use the Nimiq Web Client to build awesome apps on top of the Nimiq blockchain.",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/tutorial" },
      { label: "Live", url: "https://nimiq.guide" },
    ],
    timeline: { start: "2025-06-07", end: "2025-07-24", duration: "1m", commitCount: 53 },
    stack: ["JavaScript", "decentralization", "nimiq", "tutorial", "web-client", "tutorial-kit"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 19, examples: ["chore: release v0.0.3", "chore: add deployment script and package version to CustomTopBar"] },
      { label: "Feature development", count: 10, examples: ["feat: enhance feedback widget with improved loading checks and error handling", "feat: improve SEO meta tags"] },
      { label: "Documentation", count: 6, examples: ["docs: update README to remove emojis from section headers for improved readability", "docs: update link to tutorials"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 4, "CLOSED": 5 },
      samplePRs: [
      ],
      sampleIssues: [
        { title: "Remove seed nodes?", url: "https://github.com/nimiq/tutorial/issues/11", state: "OPEN" },
        { title: "Add link to cards", url: "https://github.com/nimiq/tutorial/issues/10", state: "OPEN" },
        { title: "explain consensus head change", url: "https://github.com/nimiq/tutorial/issues/8", state: "OPEN" },
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-06-07", updatedAt: "2025-07-24" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "prestaking-website",
    nameWithOwner: "nimiq/prestaking-website",
    role: "Contributor (Nimiq)",
    summary: "Focuses on general maintenance and tooling & dependency upkeep contributions. Recent commit: content: updated content to reflect end of pre-staking period. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/prestaking-website" },
      { label: "Live", url: "https://prestaking-website.pages.dev" },
    ],
    timeline: { start: "2024-06-10", end: "2024-11-10", duration: "5m", commitCount: 39 },
    stack: ["Vue"],
    highlights: [
      { label: "General maintenance", count: 16, examples: ["Merge pull request #13 from nimiq/onmax/security", "disable newsletter signup until we deploy nimiq.com/newsletter"] },
      { label: "Tooling & dependency upkeep", count: 15, examples: ["content: updated content to reflect end of pre-staking period", "chore: removed temporarily validator list"] },
      { label: "Feature development", count: 4, examples: ["added og things", "feat: new footer"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 11, "OPEN": 1, "CLOSED": 1 },
      issues: { "OPEN": 0, "CLOSED": 1 },
      samplePRs: [
        { title: "replaces 100 to 200", url: "https://github.com/nimiq/prestaking-website/pull/6", state: "MERGED" },
        { title: "chore: added total prestaked amount", url: "https://github.com/nimiq/prestaking-website/pull/5", state: "MERGED" },
        { title: "feat: render validator list from api", url: "https://github.com/nimiq/prestaking-website/pull/4", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "z-index hexagon issues ", url: "https://github.com/nimiq/prestaking-website/issues/1", state: "CLOSED" },
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2024-06-10", updatedAt: "2025-02-03" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "nimiq-utils",
    nameWithOwner: "nimiq/nimiq-utils",
    role: "Contributor (Nimiq)",
    summary: "Simple helper libraries for Nimiq frontends",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/nimiq-utils" },
    ],
    timeline: { start: "2022-12-19", end: "2025-05-09", duration: "2y 5m", commitCount: 38 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Feature development", count: 10, examples: ["feat: add snapshot testing for SupplyCalculator and AlbatrossPolicy RPCsg", "feat: add supply calculator RPC tests and enhance getMigrationBlockInfo function"] },
      { label: "Tooling & dependency upkeep", count: 6, examples: ["chore: move dotenv to devDependencies", "chore: added policy tests"] },
      { label: "General maintenance", count: 4, examples: ["v0.12.3", "FiatApi: export CryptoCurrencyOptions"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 5, "OPEN": 0, "CLOSED": 2 },
      issues: { "OPEN": 1, "CLOSED": 3 },
      samplePRs: [
        { title: "Support for different chain and tokens on Ethereum ", url: "https://github.com/nimiq/nimiq-utils/pull/64", state: "MERGED" },
        { title: "add supplyAt tests with rpc", url: "https://github.com/nimiq/nimiq-utils/pull/90", state: "MERGED" },
        { title: "Add GitHub Actions workflow for pkg.new", url: "https://github.com/nimiq/nimiq-utils/pull/87", state: "CLOSED" },
      ],
      sampleIssues: [
        { title: "Add `supplyAt` tests with RPC", url: "https://github.com/nimiq/nimiq-utils/issues/89", state: "CLOSED" },
        { title: "Confirm PoW and PoS Constants in policy", url: "https://github.com/nimiq/nimiq-utils/issues/88", state: "OPEN" },
        { title: "add pkg.new", url: "https://github.com/nimiq/nimiq-utils/issues/86", state: "CLOSED" },
      ],
    },
    meta: { stars: 6, license: null, createdAt: "2018-01-29", updatedAt: "2025-06-04" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "merchant-map-backend",
    nameWithOwner: "nimiq/merchant-map-backend",
    role: "Contributor (Nimiq)",
    summary: "Focuses on general maintenance contributions. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/merchant-map-backend" },
    ],
    timeline: { start: "2022-10-24", end: "2022-11-07", duration: "under 1m", commitCount: 37 },
    stack: ["PHP"],
    highlights: [
      { label: "General maintenance", count: 0, examples: ["[Add highlight summary]"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 3, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
        { title: "Create location + issue", url: "https://github.com/nimiq/merchant-map-backend/pull/6", state: "MERGED" },
        { title: "Create issue", url: "https://github.com/nimiq/merchant-map-backend/pull/5", state: "MERGED" },
        { title: "Create Crypto location", url: "https://github.com/nimiq/merchant-map-backend/pull/4", state: "MERGED" },
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2021-12-11", updatedAt: "2025-05-28" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "albatross-monkey-chaos",
    nameWithOwner: "nimiq/albatross-monkey-chaos",
    role: "Contributor (Nimiq)",
    summary: "Focuses on architecture & refactors and general maintenance contributions. Recent commit: refactor project. [Add short project summary].",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/albatross-monkey-chaos" },
    ],
    timeline: { start: "2023-03-23", end: "2023-04-27", duration: "1m", commitCount: 13 },
    stack: ["TypeScript"],
    highlights: [
      { label: "Architecture & refactors", count: 4, examples: ["refactor project", "refactor config"] },
      { label: "General maintenance", count: 4, examples: ["move config to file", "oopsie"] },
      { label: "Documentation", count: 3, examples: ["updated readme", "updated readme"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 0, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 1, license: null, createdAt: "2023-03-23", updatedAt: "2023-09-01" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "nimiq",
    owner: "nimiq",
    name: "core-rs-albatross",
    nameWithOwner: "nimiq/core-rs-albatross",
    role: "Contributor (Nimiq)",
    summary: "Rust implementation of the Albatross protocol",
    links: [
      { label: "GitHub", url: "https://github.com/nimiq/core-rs-albatross" },
      { label: "Live", url: "https://nimiq.com" },
    ],
    timeline: { start: "2023-03-17", end: "2025-02-10", duration: "1y 11m", commitCount: 10 },
    stack: ["Rust", "rust", "blockchain", "cryptography"],
    highlights: [
      { label: "Feature development", count: 5, examples: ["chore(web-client): added esm import for non-browser environments", "Added conditional serde serialization support for OutgoingStakingTransactionProof"] },
      { label: "General maintenance", count: 3, examples: ["Send log when retire validator tx is sent", "Return RPC error if there are invalid params"] },
      { label: "Documentation", count: 1, examples: ["docs: added `known_transaction_details` clarification"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 7, "OPEN": 1, "CLOSED": 1 },
      issues: { "OPEN": 1, "CLOSED": 14 },
      samplePRs: [
        { title: "Added conditional serde serialization support for OutgoingStakingTransactionProof", url: "https://github.com/nimiq/core-rs-albatross/pull/1602", state: "MERGED" },
        { title: "Add retire RPC method and log", url: "https://github.com/nimiq/core-rs-albatross/pull/1547", state: "MERGED" },
        { title: "Return RPC error if there are invalid params", url: "https://github.com/nimiq/core-rs-albatross/pull/1485", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "Add `retire_validator` method to the RPC interface", url: "https://github.com/nimiq/core-rs-albatross/issues/1542", state: "CLOSED" },
        { title: "Panic at `RPC-Server:@sendNewValidatorTransaction`", url: "https://github.com/nimiq/core-rs-albatross/issues/1483", state: "CLOSED" },
        { title: "Panic at RPC `get_slot_at`", url: "https://github.com/nimiq/core-rs-albatross/issues/1454", state: "CLOSED" },
      ],
    },
    meta: { stars: 172, license: null, createdAt: "2019-11-01", updatedAt: "2025-09-25" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "external",
    owner: "cryptocity-network",
    name: "cryptocity",
    nameWithOwner: "cryptocity-network/cryptocity",
    role: "Major External Contributor",
    summary: "Nuxt 3 Version of the Cryptocity family of websites",
    links: [
      { label: "GitHub", url: "https://github.com/cryptocity-network/cryptocity" },
    ],
    timeline: { start: "2024-08-20", end: "2025-04-15", duration: "7m", commitCount: 42 },
    stack: ["Vue"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 13, examples: ["chore: the use of v-deep is deprecated", "chore: convert München to Munich for supabase query"] },
      { label: "Feature development", count: 8, examples: ["Merge pull request #15 from cryptocity-network/feature/employee-contact-cards", "feature: add phone number and whatsapp to contact cards"] },
      { label: "Bug fixing", count: 3, examples: ["fix: show the correct total number of locations", "fix: normalize sao-paulo"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 2, "OPEN": 0, "CLOSED": 1 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
        { title: "feat: use pagination in locations", url: "https://github.com/cryptocity-network/cryptocity/pull/11", state: "MERGED" },
        { title: "Onmax/locations pagination", url: "https://github.com/cryptocity-network/cryptocity/pull/10", state: "CLOSED" },
        { title: "chore: add portuguese", url: "https://github.com/cryptocity-network/cryptocity/pull/14", state: "MERGED" },
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2024-01-17", updatedAt: "2025-04-16" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "external",
    owner: "cryptocity-network",
    name: "Cryptocity.exchange",
    nameWithOwner: "cryptocity-network/Cryptocity.exchange",
    role: "Major External Contributor",
    summary: "Buy and sell NIM, Bitcoin, USDC, and USDT with Euro, USD, CHF, and more on Cryptocity.",
    links: [
      { label: "GitHub", url: "https://github.com/cryptocity-network/Cryptocity.exchange" },
      { label: "Live", url: "https://cryptocity.exchange" },
    ],
    timeline: { start: "2025-04-21", end: "2025-05-20", duration: "under 1m", commitCount: 40 },
    stack: ["Vue", "crypto", "crypto-exchange", "nimiq", "cryptocity"],
    highlights: [
      { label: "Tooling & dependency upkeep", count: 23, examples: ["Update en.json", "Merge pull request #25 from cryptocity-network/dev"] },
      { label: "Bug fixing", count: 7, examples: ["fix: update wallet creation text in Spanish localization and improve widget styling", "fix: enhance Coinify and Letsexchange widgets with loading states and client-side rendering"] },
      { label: "Architecture & refactors", count: 4, examples: ["refactor: enhance layout responsiveness for footer and banners", "refactor: update wallet CTA height for better responsiveness"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 5, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 1, "CLOSED": 12 },
      samplePRs: [
        { title: "fix: enhance Coinify and Letsexchange widgets with loading states and…", url: "https://github.com/cryptocity-network/Cryptocity.exchange/pull/25", state: "MERGED" },
        { title: "Package updates", url: "https://github.com/cryptocity-network/Cryptocity.exchange/pull/20", state: "MERGED" },
        { title: "Updated copy & translations", url: "https://github.com/cryptocity-network/Cryptocity.exchange/pull/19", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "Update privacy and term and conditions", url: "https://github.com/cryptocity-network/Cryptocity.exchange/issues/24", state: "CLOSED" },
        { title: "Toggle swap/buy", url: "https://github.com/cryptocity-network/Cryptocity.exchange/issues/22", state: "CLOSED" },
        { title: "Update Footer UI", url: "https://github.com/cryptocity-network/Cryptocity.exchange/issues/21", state: "CLOSED" },
      ],
    },
    meta: { stars: 0, license: null, createdAt: "2025-02-08", updatedAt: "2025-05-20" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "external",
    owner: "unovue",
    name: "reka-ui",
    nameWithOwner: "unovue/reka-ui",
    role: "External Open Source Contributor",
    summary: "An open-source UI component library for building high-quality, accessible design systems and web apps for Vue. Previously Radix Vue",
    links: [
      { label: "GitHub", url: "https://github.com/unovue/reka-ui" },
      { label: "Live", url: "https://reka-ui.com" },
    ],
    timeline: { start: "2023-07-14", end: "2025-03-15", duration: "1y 8m", commitCount: 13 },
    stack: ["Vue", "accessible", "design-system", "headless", "primitives", "ui", "ui-kit", "vue", "component-library", "nuxt", "radix-ui", "ui-components", "vue-radix", "accessibility", "vue-components", "vue-component-library", "reka-ui"],
    highlights: [
      { label: "Feature development", count: 6, examples: ["docs(migration): add section for nuxt module (#1712)", "feat(TagsInput): added support for object in tags input (#863)"] },
      { label: "Tooling & dependency upkeep", count: 3, examples: ["chore: fix lint issues (#879)", "chore: use correct duration class (#865)"] },
      { label: "Bug fixing", count: 1, examples: ["[Bug] fix: Toggle value "] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 13, "OPEN": 0, "CLOSED": 2 },
      issues: { "OPEN": 0, "CLOSED": 5 },
      samplePRs: [
        { title: "chore: update Tooltip to use Portal instead of Teleport", url: "https://github.com/unovue/reka-ui/pull/370", state: "MERGED" },
        { title: "[useSingleOrMultiple] fix: Toogle value", url: "https://github.com/unovue/reka-ui/pull/264", state: "MERGED" },
        { title: "[Popover]feat: 2/3(Complete API)", url: "https://github.com/unovue/reka-ui/pull/251", state: "CLOSED" },
      ],
      sampleIssues: [
        { title: "[Bug]: Tooltip colliding with window border", url: "https://github.com/unovue/reka-ui/issues/393", state: "CLOSED" },
        { title: "[Bug]: Click to open in DropdownMenu triggers click in the items", url: "https://github.com/unovue/reka-ui/issues/366", state: "CLOSED" },
        { title: "[Bug]: Missing `as-child` Prop in `PopperArrow` ", url: "https://github.com/unovue/reka-ui/issues/353", state: "CLOSED" },
      ],
    },
    meta: { stars: 5583, license: null, createdAt: "2023-06-22", updatedAt: "2025-09-29" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "external",
    owner: "DavidHDev",
    name: "vue-bits",
    nameWithOwner: "DavidHDev/vue-bits",
    role: "External Open Source Contributor",
    summary: "An open source collection of animated, interactive & fully customizable Vue components for building stunning, memorable websites.",
    links: [
      { label: "GitHub", url: "https://github.com/DavidHDev/vue-bits" },
      { label: "Live", url: "https://vue-bits.dev/" },
    ],
    timeline: { start: "2025-07-11", end: "2025-09-17", duration: "2m", commitCount: 13 },
    stack: ["Vue", "javascript", "tailwind", "tailwindcss", "typescript", "ui-components", "ui-library", "vue", "vue3", "vuejs", "vuejs-components", "vuejs3"],
    highlights: [
      { label: "Feature development", count: 12, examples: ["feat: move DomeGallery styles to Tailwind classes", "feat: add InfiniteMenu component"] },
      { label: "Bug fixing", count: 1, examples: ["fix linter"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 10, "OPEN": 0, "CLOSED": 2 },
      issues: { "OPEN": 0, "CLOSED": 0 },
      samplePRs: [
        { title: "feat: add DomeGallery component", url: "https://github.com/DavidHDev/vue-bits/pull/98", state: "MERGED" },
        { title: "feat: add InfiniteMenu component", url: "https://github.com/DavidHDev/vue-bits/pull/97", state: "MERGED" },
        { title: "feat: add GradientBlinds background component", url: "https://github.com/DavidHDev/vue-bits/pull/96", state: "CLOSED" },
      ],
      sampleIssues: [
      ],
    },
    meta: { stars: 2567, license: null, createdAt: "2025-07-07", updatedAt: "2025-09-29" },
    impact: "[Add impact / results / adoption details]",
  },
  {
    category: "external",
    owner: "nuxt-hub",
    name: "core",
    nameWithOwner: "nuxt-hub/core",
    role: "External Open Source Contributor",
    summary: "Build full-stack applications with Nuxt, with almost zero-config.",
    links: [
      { label: "GitHub", url: "https://github.com/nuxt-hub/core" },
      { label: "Live", url: "https://hub.nuxt.com" },
    ],
    timeline: { start: "2024-04-11", end: "2024-11-04", duration: "6m", commitCount: 7 },
    stack: ["TypeScript", "cloudflare", "nuxt", "vue", "full-stack", "d1", "kv", "r2", "ssr", "nuxthub", "workers-ai"],
    highlights: [
      { label: "Documentation", count: 5, examples: ["docs: Update `vectorize.dimensions` example to numbers (#362)", "docs: prerender dynamic pages using modules (#300)"] },
      { label: "Tooling & dependency upkeep", count: 1, examples: ["chore: clean zod validation in database api endpoints (#109)"] },
    ],
    collaboration: {
      pullRequests: { "MERGED": 6, "OPEN": 0, "CLOSED": 0 },
      issues: { "OPEN": 0, "CLOSED": 12 },
      samplePRs: [
        { title: "docs(prerendering): dynamic pages using modules", url: "https://github.com/nuxt-hub/core/pull/300", state: "MERGED" },
        { title: "chore: clean zod validation in database api endpoints", url: "https://github.com/nuxt-hub/core/pull/109", state: "MERGED" },
        { title: "docs: Add seed configuration for database population with Nitro Tasks", url: "https://github.com/nuxt-hub/core/pull/107", state: "MERGED" },
      ],
      sampleIssues: [
        { title: "Unable to create new projects using Nuxt Hub Team", url: "https://github.com/nuxt-hub/core/issues/299", state: "CLOSED" },
        { title: "\"Roadmap\" is not showing links", url: "https://github.com/nuxt-hub/core/issues/253", state: "CLOSED" },
        { title: "[DevTools]: Database table is not reactive when adding rows using a Nitro Task", url: "https://github.com/nuxt-hub/core/issues/108", state: "CLOSED" },
      ],
    },
    meta: { stars: 1166, license: null, createdAt: "2024-02-20", updatedAt: "2025-09-26" },
    impact: "[Add impact / results / adoption details]",
  },
];
