name: Deploy to NuxtHub
on:
  push:
    branches:
      - main
    paths:
      - 'demos/realtime-emojis/**'
      - '.github/workflows/nuxthub.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: nuxthub-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: demos/realtime-emojis

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: demos/realtime-emojis/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Ensure NuxtHub module is installed
        run: pnpx nuxthub@latest ensure

      - name: Build & Deploy to NuxtHub
        if: ${{ secrets.NUXTHUB_PROJECT_KEY != '' }}
        uses: nuxt-hub/action@v2
        with:
          project-key: ${{ secrets.NUXTHUB_PROJECT_KEY }}
          directory: demos/realtime-emojis
